name: Build

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: '8'
        cache: 'sbt'

    - name: AWS Auth
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
        aws-region: eu-west-1

    - name: Test and build
      run: |
        sbt clean compile test universal:packageBin

    - name: Upload to riff-raff
      uses: guardian/actions-riff-raff@v2
      with:
        configPath: riff-raff.yaml
        projectName: Editorial Tools::sponsorship-expiry-email-lambda
        buildNumberOffset: 37 # This is the last build number from TeamCity
        contentDirectories: |
          sponsorship-expiry-email-lambda:
          - target/universal/sponsorship-expiry-email-lambda.zip